# Rabi_GG_LNV configuration file

[soc]
lnv_ch = 0
ref_ch = 2
mw_ch = 4

CNT1_memory = [0, 1]
mw_gain = 3000
reps = 6000
mw_freq = 2865.51
pi_pulse = 97.27

# not used, but nesessary 
init_len = 5000
ro_len = 700         #apd readout time
dwell_left = 1000
dwell_right = 800

mw_offset = 0

lnv_delay = 110
mw_delay = 100
apd_delay = 300

#Rabi
#Sequence (width = ns)
init_gain = 20000       #minus voltage, laser ON
init_width = 20000      #duration of ON

free_gain = -20000       #off-laser voltage

readout_gain = 20000    #laser ON: read out
readout_width = 1000     #laser ON: duration of readout

after_gain = -20000      #??? laser OFF
after_width = 1000      #??? length of OFF

term_ref_sig = 0
term_contrast = 1000
term_after_sig = 0

[pc]
# tau sweep range in ns (tau should be larger than ~10)
start = 10
end = 80000
step = 1000

iteration = 1000
autofocus = false
autofocus_period = 9999
shuffle = false