# PODMR_LNV configuration file

[soc]
lnv_ch1 = 0
lnv_ch2 = 2
mw_ch = 4

CNT1_memory = [0, 1]
mw_gain = 5000
reps = 10000

# not used, but nesessary 
init_len = 3000
ro_len = 3000
dwell_left = 100
dwell_right = 100

mw_offset = 0
mw_len = 10
mw_delay = 0
apd_delay = 20
 
#PODMR
#Sequence (width = ns)
init_gain = 26000
init_width = 3000
free_gain = -27000
free_width = 3000
readout_gain = 26000
readout_width = 3000
after_gain = -27000
after_width = 3000


[pc]
# frequency sweep range in MHz
start = 2600
end = 2602
step = 1

iteration = 10000
autofocus = false
autofocus_period = 9999
shuffle = false