# Rabi configuration file

[soc]
mw_ch = 4
green_ch = 5

green_gain = 30000
mw_gain = 3000 # 

mw_freq = 2832  # in MHz
CNT1_memory = [0, 1]
reps = 30000

spin_init_time = 2000
ro_len = 300
dwell_left = 1000
dwell_right = 1000
mw_offset = 0
green_delay = 0
mw_delay = 150
apd_delay = 300

[pc]
# tau sweep range in ns (tau should be larger than ~10)
start = 10
end = 1000
step = 10

iteration = 100
autofocus = false
autofocus_period = 9999
shuffle = false